JsonDataProject/JsonDataProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

JsonDataProject/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('read/', views.read_data_from_file, name='read-file'),
]

JsonDataProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

JsonDataProject/api/models.py
from django.db import models

# Create your models here.


class Employee(models.Model):
    employee_id = models.CharField(unique=True, max_length=20)
    real_name = models.CharField(max_length=50)
    tz = models.CharField(max_length=50)

    def __str__(self):
        return str(self.real_name)+" "+str(self.employee_id)


class ActivityPeriods(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __str__(self):
        return str(self.start_time)

JsonDataProject/api/views.py
import json

from django.shortcuts import render
from django.http import HttpResponse

from .sample import get_source
from .models import Employee, ActivityPeriods

# Create your views here.


def index(request):
    employee = Employee.objects.all()
    return render(request, 'api/index.html', {"employee_list": employee})


def read_data_from_file(request):

    get_source('api/json_data_file')

    return HttpResponse("success")

JsonDataProject/api/templates/api/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for employee in employee_list %}
<ul>
    <li>{{employee.real_name}}<br></li>
    <li>{{employee.employee_id}}<br></li>
    <li>{{employee.tz}}<br></li>
        <li>
            <ol>
                {% for activity in employee.activityperiods_set.all %}
                <li>start time:{{activity.start_time}}</li>
                <li>end time:{{activity.end_time}}</li>
        {% endfor %}</li>
</ul>
<br><br>

{% endfor %}
</body>
</html>